-
  name: Install and configure MySQL
  hosts: target1
  become: yes

  vars:
    db_name: testdb
    mysql_user_name: user
    mysql_user_password: Passw0rd
  
  tasks:
    - name: Install PreReq packages
      vars:
        packages:
          - epel-release
          - yum-utils
      yum: name='{{ packages }}' state=present
    - name: Add repository
      yum_repository:
        name: MariaDB
        description: MariaDB Cuctom repository
        baseurl: http://yum.mariadb.org/10.5/centos-amd64/
        gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
        gpgcheck: yes
    - name: Install MySQL packages
      vars: 
        packages:
          - MariaDB-server
          - MariaDB-client
          - MySQL-python
      yum: name='{{ packages }}' state=present

    - name: Start MySQL service
      service: name=mariadb state=started

    - name: Configure db 
      mysql_db: name='{{ db_name }}' state=present
    
    - name: Create db user
      mysql_user:
        name: '{{ mysql_user_name }}'
        password: '{{ mysql_user_password }}'
        priv: '{{ db_name }}.*:ALL'
        state: present
        